# Generated by Django 5.2.8 on 2025-11-12 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_doctorprofile_created_at_doctorprofile_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='review_note',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='registration_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
