# Generated by Django 5.2.8 on 2025-11-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_doctorprofile_review_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user',
            field=models.CharField(max_length=80),
        ),
    ]
