# Generated by Django 5.2.8 on 2025-11-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Optional path inside the site', max_length=255),
        ),
    ]
